<?php

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function islandora8_issue_1280_form_field_ui_field_storage_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['field_type_descriptions'] = array(
    '#type' => 'table',
    '#header' => array( 'Field type', 'Description'),
  );

  $field_type_descriptions = array(
    'Authority Link' => 'Some helpful text goes here.',
    'Boolean' => "Some helpful text goes here.",
    'Comments' => "Some helpful text goes here.",
    'Content' => "Some helpful text goes here.",
    'Date' => "Some helpful text goes here.",
    'EDTF' => "Some helpful text goes here.",
    'Email' => "Some helpful text goes here.",
    'Geolocation' => "Some helpful text goes here.",
    'Link' => "Some helpful text goes here.",
    'Media' => "Some helpful text goes here.",
    'Name' => "Some helpful text goes here.",
    'Taxonomy term' => "Some helpful text goes here.",
    'Timestamp' => "Some helpful text goes here.",
    'Typed relation' => "Some helpful text goes here.",
    'User' => "Some helpful text goes here.",
  );

  foreach ($field_type_descriptions as $field_type => $description) {
    $form['field_type_descriptions']['#rows'][$field_type] = array($field_type, $description);
  }
}
